### ISSUE TITLE
wavの長さとmonophone label の長さの不一致

### ISSUE THREAD

**Issue by CHI-TA** [AmanoKei/Natsume_Singing#1]
すべてのモノフォンラベルに影響するかもしれませんが、wav波形の長さとラベルの長さが一致しません。
最後のpauが長すぎることが多いようです。

**Comment by AmanoKei** [comment]
修正しました！(もしかしたら抜けがあるかもしれませんのでその場合は申し訳ないです……)

**Comment by CHI-TA** [comment]
修正(本当に)お疲れさまです。github側も更新しますか？

**Comment by AmanoKei** [comment]
fetchするの忘れてました……(更新完了しました)

**Comment by CHI-TA** [comment]
ありがとうございます！
